Fix computeSolution inputs in OpenLIFUSonicationPlanner.py
Closes #161

Fixes the usage of `get_current_data()` within
`OpenLIFUSonicationPlannerWidget.onComputeSolutionClicked(self)` to
use the dictionary returned by `get_current_data()`.

A prior implementation of `get_current_data()` returned a dictionary as
opposed to a tuple. Therefore, when attempting to perform "Compute
sonication solution" after loading a session in
`SlicerWithSlicerOpenLIFU`, the following error message occurred:

```
Traceback (most recent call last):
  File "/Users/user/projects/ow/SlicerOpenLIFU-Debug/lib/Slicer-5.7/qt-scripted-modules/OpenLIFUSonicationPlanner.py", line 297, in onComputeSolutionClicked
    self.logic.computeSolution(activeVolume, activeTarget, activeTransducer, activeProtocol)
  File "/Users/user/projects/ow/SlicerOpenLIFU-Debug/lib/Slicer-5.7/qt-scripted-modules/OpenLIFUSonicationPlanner.py", line 516, in computeSolution
    inputProtocol.protocol,
AttributeError: 'str' object has no attribute 'protocol'
```

This commit fixes the corresponding error message within the
`SlicerWithSlicerOpenLIFU` app.